### ISSUE TITLE
Package leans on abandoned and unmaintained bitpay "SDK"

### ISSUE THREAD

**Issue by petski** [hiqdev/omnipay-bitpay#1]
See https://packagist.org/packages/bitpay/php-client:

>  This package is abandoned and no longer maintained. The author suggests using the bitpay/sdk package instead.

**Comment by hiqsol** [comment]
Fortunately it is still able to work.
Thanks for information! We'll take of it when we have time.

**Comment by SilverFire** [comment]
Switched to a new version of API
